version: '3.9'


services:
  stocks_api:
    container_name: stocks_api
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - ./src/:/src/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432


volumes:
  postgres_data: