# Generated by Django 4.1 on 2022-09-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNews',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('stock', models.TextField(max_length=5)),
                ('headline', models.TextField(null=True)),
                ('image', models.URLField(max_length=300, null=True)),
                ('summary', models.TextField(null=True)),
                ('source', models.TextField()),
                ('url', models.URLField(max_length=300)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
